config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  resources :users
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  resources :projects, only: [:create, :destroy, :update] do
    resources :participations, only: [:create] do
    end
    resources :comments, only: [:create]
    get 'comments/:id', to: 'comments#show'
  end

  get '/projects/new', to: 'projects#new'
  get '/projects/:id', to: 'projects#show'
  get '/projects/edit/:id', to: 'projects#edit', as: "edit_project"


  delete '/commentout/:id', to: 'comments#destroy', as: "commentout"
  delete '/nonparticipation/:project_id/:id', to: 'participations#destroy', as: 'nonparticipation'

  get '/timekeep', to: 'time_keeps#show'
  post '/timekeep', to: 'time_keeps#create'
  get 'monthly', to: 'time_keeps#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  root 'home#home'
  get 'index', to: 'home#index'
  get 'about', to: 'home#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :participations, dependent: :destroy
  has_many :participation_users, through: :participations, source: :user

  has_one_attached :image
  default_scope -> { order(created_at: :desc) }

  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 150 }
  validates :content, presence: true
  validates :start_on, presence: true
  validates :end_on, presence: true

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    before_action :logged_in_user, only: [:new, :create, :edit, :destroy]
    before_action :correct_user, only: [:edit, :destroy, :update]

    def new
        @project = current_user.projects.build
    end

    def show
        @project = Project.find_by(id: params[:id])
        @participation = @project.participations.build
        @participation_users = @project.participation_users
        @comment = @project.comments.build
        @comments = @project.comments.all
        if logged_in?
          @sanka = Participation.find_by(user_id: current_user.id,
                                         project_id: @project.id)
        end
    end

    def create
        @project = current_user.projects.build(project_params)
        @project.image.attach(params[:project][:image])
        if @project.end_on && @project.start_on
          sabun = (@project.end_on - @project.start_on).to_i
          if sabun > 0
            if @project.save
                flash[:success] = "ケツイを力に変えるんだ！"
                redirect_to root_url
            else
                render "new"
            end
          else
            flash[:error] = "日程が正しくありません"
            render "new"
          end
        else
          flash[:error] = "日程を選択しなよ"
          render 'new'
        end
    end

    def destroy
        if @project.destroy
          flash[:success] = "プロジェクトを削除しました"
          redirect_to root_url
        else
          render "current_user_path"
        end
    end

    def edit
      @project = Project.find_by(id: params[:id])
    end

    def update
      @project = Project.find_by(id: params[:id])
      if @project.update(update_params)
        flash[:success] = "update!"
        redirect_to root_url
      else
        render "edit"
      end
    end

    private

      def project_params
        params.require(:project).permit(:title, :content, :g_url, :start_on, :end_on, :image)
      end

      def update_params
        params.require(:project).permit(:title, :content, :g_url, :start_on, :end_on, :image, :finish)
      end

      #他のユーザーが編集、削除できないようにする
      def correct_user
          @project = current_user.projects.find_by(id: params[:id])
          redirect_to root_url if @project.nil?
      end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/edit.html.erb
<%= form_with(model: @project, local: true) do |f| %>

  <div class="mobile-title">
    <div class="mobile-t">
      <h1>Project Edit</h1>
      <p>...完成したらチェックをつけなよ</p>
    </div>
  </div>

  <div class="title">
    <% if !@project.errors.any? %>
      <%= image_tag 'メタトン.jpg', class: 'bugerpant' %>
    <% else %>
      <%= image_tag 'metaton.jpg', class: 'bugerpant' %>
    <% end %>
    <div class="selif-left">
      <%= render "shared/error_message", object: f.object %>
      <% if !@project.errors.any? %>
       <p>Projectを編集するんだね？</p>
       <p>完成したならチェックボタンをおしなよ</p>
      <% end %>
    </div>
  </div>

  <div class="undertale">

    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control', placeholder: "Compose new title..." %>
    </div>

    <div class="form-group">
      <%= f.label :github %>
      <%= f.text_field :g_url, class: 'form-control', placeholder: "githubのurl..." %>
    </div>

    <div class="form-group">
      <%= f.label :content %>
      <%= f.text_area :content, class: 'form-control', placeholder: "Compose new micropost..." %>
    </div>

    <span class="image">
      <%= f.file_field :image, accept: "image/jpeg,image/gif,image/png" %>
    </span>

    <div class="form-group">
      <%= f.check_box :finish, {class: "check_box"}, "true", "false" %>
      <%= f.label :完成 %>
    </div>

    <div class="form-group">
      <%= f.label :開始日 %>
      <%= f.date_field :start_on %>
    </div>

    <div class="form-group">
      <%= f.label :期限日 %>
      <%= f.date_field :end_on %>
    </div>

    <%= f.submit "SAVE", class: "btn btn-border" %>

  </div>


<% end %>

app/views/projects/new.html.erb
<%= form_with(model: @project, local: true) do |f| %>

  <div class="mobile-title">
    <div class="mobile-t">
      <h1>New Project</h1>
      <p>...最高のアイデアを期待しているよ</p>
    </div>
  </div>

  <div class="title">
    <% if !@project.errors.any? %>
      <%= image_tag 'メタトン.jpg', class: 'bugerpant' %>
    <% else %>
      <%= image_tag 'metaton.jpg', class: 'bugerpant' %>
    <% end %>
    <div class="selif-left">
      <%= render "shared/error_message", object: f.object %>
      <% if !@project.errors.any? %>
       <p>新しいプロジェクトを作成するんだね？</p>
       <p>最高の構想を期待してるよ</p>
      <% end %>
    </div>
  </div>

  <div class="undertale">

    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control', placeholder: "Compose new title..." %>
    </div>

    <div class="form-group">
      <%= f.label :github %>
      <%= f.text_field :g_url, class: 'form-control', placeholder: "githubのurl..." %>
    </div>

    <div class="form-group">
      <%= f.label :content %>
      <%= f.text_area :content, class: 'form-control', placeholder: "Compose new micropost..." %>
    </div>

    <div class="form-group">
      <%= f.label :開始日 %>
      <%= f.date_field :start_on %>
    </div>

    <div class="form-group">
      <%= f.label :期限日 %>
      <%= f.date_field :end_on %>
    </div>

    <%= f.submit "Post", class: "btn btn-border" %>

    <span class="image">
    <%= f.file_field :image, accept: "image/jpeg,image/gif,image/png" %>
    </span>

  </div>


<% end %>

app/views/projects/show.html.erb
<div class="undertale">
  <div class="project-title">
    <%= @project.title %>
    <% if @project.finish == true %>
      <small>finish</small>
    <% else %>
      <small><%= @project.start_on %>~<%= @project.end_on %></small>
    <% end %>
  </div>
  <div class="command">
    <%= link_to @project.user.name, user_path(@project.user.id) %>
    <%= link_to "Github", @project.g_url %>
    <% if logged_in? %>
      <% if current_user.already_paticipationed?(@project) %>
        <%= link_to "不参加", nonparticipation_path(project_id: @project.id, id: current_user.id), method: :delete %>
      <% else %>
        <%= link_to "参加", project_participations_path(@project), method: :post %>
      <% end %>
      <% if current_user.id == @project.user.id %>
        <%= link_to "edit", edit_project_path(@project) %>
        <%= link_to "destroy", project_path, method: :delete %>
      <% end %>
    <% end %>
  </div>
  <% if @participation_users.any? %>
    <%= render "layouts/dropdown_users" %>
  <% end %>
  <% if @project.image.attached? %>
    <div class="project-image">
      <%= image_tag @project.image %>
    </div>
  <% end %>
  <%= simple_format(@project.content, class: "project-content") %>
  <% if @comments %>
    <% @comments.each do |comment| %>
      <div class="comment-content">
        <small>
          <%= comment.created_at.strftime('%m/%d') %>
          <%= link_to comment.user.name, user_path(comment.user.id) %>
          <%= link_to "destroy", commentout_path(comment.id), method: :delete %>
        </small>
        <br><%= comment.content %></br>
      </div>
    <% end %>
  <% end %>

</div>

<% if logged_in? %>
  <%= form_with(model: [@project, @comment], local: true)do |f| %>
    <div class="undertale">
      <div class="form-group">
        <%= f.label :comment %>
        <%= f.text_field :content, class: "form-control" %>
      </div>

      <%= f.submit "Post", class: "btn btn-border" %>
    </div>

  <% end %>
<% end %>