config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  resources :users
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  resources :projects, only: [:create, :destroy, :update] do
    resources :participations, only: [:create] do
    end
    resources :comments, only: [:create]
    get 'comments/:id', to: 'comments#show'
  end

  get '/projects/new', to: 'projects#new'
  get '/projects/:id', to: 'projects#show'
  get '/projects/edit/:id', to: 'projects#edit', as: "edit_project"


  delete '/commentout/:id', to: 'comments#destroy', as: "commentout"
  delete '/nonparticipation/:project_id/:id', to: 'participations#destroy', as: 'nonparticipation'

  get '/timekeep', to: 'time_keeps#show'
  post '/timekeep', to: 'time_keeps#create'
  get 'monthly', to: 'time_keeps#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  root 'home#home'
  get 'index', to: 'home#index'
  get 'about', to: 'home#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_dropdown_users.html.erb
<div class="dropdown_body dropright">
  <a class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    参加者
  </a>
  <div class="dropdown-menu">
    <% @participation_users.each do |f| %>
      <ul>
        <li>
          <%= image_tag "heart.png" %>
          <%= link_to f.name, user_path(f) %>
        </li>
      </ul>  
    <% end %>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-light" style="background-color: #555555;">
    <div class="container">
        <%= link_to "Home", root_path %>
        <%= link_to "About", about_path %>
        <% if logged_in? %>
          <%= link_to current_user.name, user_path(current_user) %>
          <div class="dropdown">
            <button class="btn" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <li>Menu</li>
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <li><%= link_to "user edit", edit_user_path(current_user) %></li>
              <li><%= link_to "new project", projects_new_path %></li>
              <li><%= link_to "Log out", logout_path, method: :delete %></li>
            </div>
          </div>
        <% else %>
          <%= link_to "Sign up", signup_path %>
          <%= link_to "Login", login_path %>
        <% end %>
    </div>
</nav>

app/views/layouts/_nav_home.html.erb
<nav>
  <div class="nav nav-tabs" id="nav-tab" role="tablist">
    <a class="nav-item nav-link active" id="nav-project-tab" data-toggle="tab" href="#nav-project" role="tab" aria-controls="nav-project" aria-selected="true">プロジェクト一覧</a>
    <a class="nav-item nav-link" id="nav-user-tab" data-toggle="tab" href="#nav-user" role="tab" aria-controls="nav-user" aria-selected="false">ユーザー一覧</a>
    <a class="nav-item nav-link" id="nav-contact-tab" data-toggle="tab" href="#nav-contact" role="tab" aria-controls="nav-contact" aria-selected="false">Contact</a>
  </div>
</nav>
<div class="tab-content" id="nav-tabContent">
  <div class="tab-pane fade show active" id="nav-project" role="tabpanel" aria-labelledby="nav-project-tab">
    <% @projects.each do |project| %>
      <p class="project-title">
        *<%= link_to project.title, project %>
      </p>
    <% end %>
    <%= paginate @projects %>
  </div>
  <div class="tab-pane fade" id="nav-user" role="tabpanel" aria-labelledby="nav-user-tab">
    <div class="card-text">
    <% @users.each do |user| %>
      <li>
        <%= link_to user do %>
          <%= image_tag "heart.png" %>
          <%= user.name %>
        <% end %>
      </li>
    <% end %>
    </div>
  </div>
  <div class="tab-pane fade" id="nav-contact" role="tabpanel" aria-labelledby="nav-contact-tab">
    <% @projects.each do |project| %>
      <% if project.finish == false %>
        <p class="project-title">
          *<%= link_to project.title, project %>
          <small style="color: yellow;"><%= project.start_on %>~<%= project.end_on %></small>
        </p>
      <% end %>
    <% end %>
  </div>
</div>

app/views/layouts/_nav_user_show.html.erb
<nav>
  <div class="nav nav-tabs" id="nav-tab" role="tablist">
    <a class="nav-item nav-link" id="nav-project-tab" data-toggle="tab" href="#nav-project" role="tab" aria-controls="nav-home" aria-selected="false">Created</a>
    <a class="nav-item nav-link" id="nav-participation-tab" data-toggle="tab" href="#nav-participation" role="tab" aria-controls="nav-participation" aria-selected="false">Participationed</a>
    <a class="nav-item nav-link active" id="nav-contact-tab" data-toggle="tab" href="#nav-contact" role="tab" aria-controls="nav-contact" aria-selected="true">Active</a>
  </div>
</nav>
<div class="tab-content" id="nav-tabContent">
  <div class="tab-pane fade" id="nav-project" role="tabpanel" aria-labelledby="nav-project-tab">
    <% @projects.each do |project| %>
      <p class="project-title">*<%= link_to project.title, project %></p>
      <% if project.image.attached? %>
        <div class="project-image">
          <%= image_tag project.image %>
        </div>
      <% end %>
      <%= simple_format(project.content, class: "project-content") %>
    <% end %>
    <%= paginate @projects %>
  </div>
  <div class="tab-pane fade" id="nav-participation" role="tabpanel" aria-labelledby="nav-participation-tab">
    <% if @participation_projects.any? %>
      <% @participation_projects.each do |f| %>
        <div class="project-title">
          *<%= link_to f.title, project_path(f) %>
        </div>
        <% if f.image.attached? %>
          <div class="project-image">
            <%= image_tag f.image %>
          </div>
        <% end %>
        <%= simple_format(f.content, class: "project-content") %>
      <% end %>
    <% end %>
  </div>
  <div class="tab-pane fade show active" id="nav-contact" role="tabpanel" aria-labelledby="nav-contact-tab">
    <% if @participation_projects.any? %>
      <% @participation_projects.each do |f| %>
        <% if f.finish  == false %>
          <div class="project-title">
            *<%= link_to f.title, project_path(f), style: "color: red;" %>
            <small style="color: yellow;"><%= f.start_on %>~<%= f.end_on %></small>
          </div>
          <% if f.image.attached? %>
            <div class="project-image">
              <%= image_tag f.image %>
            </div>
          <% end %>
          <%= simple_format(f.content, class: "project-content") %>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/layouts/_serch.html.erb
<%= search_form_for @q, url: user_path(@user) do |f| %>
  <div style="display: inline-flex">
  <div class="form-group">
    <%= f.search_field :title_cont, class: "form-control", placeholder: '検索ワード' %>
    </div>
    <%= f.submit "SERCH", class: "btn btn-border", style: "margin: 0;" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectToDo</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>